In [1]:
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier

import pandas as pd
import numpy as np
np.random.seed(0)

In [2]:
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [3]:
#tambahkan kolom baru untuk nama spesies
df['species'] = pd.Categorical.from_codes(iris.target, iris.target_names)
df.tail(70)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
80,5.5,2.4,3.8,1.1,versicolor
81,5.5,2.4,3.7,1.0,versicolor
82,5.8,2.7,3.9,1.2,versicolor
83,6.0,2.7,5.1,1.6,versicolor
84,5.4,3.0,4.5,1.5,versicolor
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica
149,5.9,3.0,5.1,1.8,virginica

In [4]:
df['is_train'] = np.random.uniform(0,1,len(df)) <= .75
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species,is_train
0,5.1,3.5,1.4,0.2,setosa,True
1,4.9,3.0,1.4,0.2,setosa,True
2,4.7,3.2,1.3,0.2,setosa,True
3,4.6,3.1,1.5,0.2,setosa,True
4,5.0,3.6,1.4,0.2,setosa,True

In [5]:
#membagi dataframes dengan data latih dan data uji
train, test = df[df['is_train']==True], df[df['is_train']==False]
#tampilkan total pengamatan untuk dataframes latih dan uji
print("Total pengamatan pada Data Training", len(train))
print("Total pengamatan pada Data Uji", len(test))

Total pengamatan pada Data Training 118
Total pengamatan pada Data Uji 32

In [6]:
features = df.columns[:4]
features

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [7]:
y = pd.factorize(train['species'])[0]
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [8]:
clf = RandomForestClassifier(n_jobs=2, random_state=0)

clf.fit(train[features], y)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=2,
                       oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [9]:
clf.predict(test[features])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [12]:
test[features].shape

(32, 4)

In [13]:
test[features]

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
7                  5.0               3.4                1.5               0.2
8                  4.4               2.9                1.4               0.2
10                 5.4               3.7                1.5               0.2
13                 4.3               3.0                1.1               0.1
17                 5.1               3.5                1.4               0.3
18                 5.7               3.8                1.7               0.3
19                 5.1               3.8                1.5               0.3
20                 5.4               3.4                1.7               0.2
21                 5.1               3.7                1.5               0.4
23                 5.1               3.3                1.7               0.5
27                 5.2               3.5                1.5               0.2
31                 5.4               3.4                1.5               0.4
38                 4.4               3.0                1.3               0.2
52                 6.9               3.1                4.9               1.5
66                 5.6               3.0                4.5               1.5
68                 6.2               2.2                4.5               1.5
70                 5.9               3.2                4.8               1.8
72                 6.3               2.5                4.9               1.5
89                 5.5               2.5                4.0               1.3
98                 5.1               2.5                3.0               1.1
103                6.3               2.9                5.6               1.8
109                7.2               3.6                6.1               2.5
111                6.4               2.7                5.3               1.9
114                5.8               2.8                5.1               2.4
116                6.5               3.0                5.5               1.8
118                7.7               2.6                6.9               2.3
122                7.7               2.8                6.7               2.0
140                6.7               3.1                5.6               2.4
143                6.8               3.2                5.9               2.3
144                6.7               3.3                5.7               2.5
147                6.5               3.0                5.2               2.0
149                5.9               3.0                5.1               1.8

In [14]:
clf.predict_proba(test[features])[0:10]

array([[1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.95, 0.05, 0.  ],
       [1.  , 0.  , 0.  ],
       [0.99, 0.01, 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ]])